version: 0.0.1
jobs:
  build:
    docker:
      - image: circleci/node:9.11.2-stretch

    working_directory: ~/repo/citadel_core

    steps:
      - checkout
        
      - run:
          name: Preparing to build
          command: |
            sudo npm i -g npm npx
        
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-

      - run:
          name: Installing dependencies
          command: |
            npm i
            
      - run:
          name: Building apidoc
          command: |
            npx apidoc -e node_modules

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
        
        
      - run:
          name: Deploying
          command: |
            zip -r citadel_core.zip ./

            scp -oStrictHostKeyChecking=no citadel_core.zip ${ssh_connection}:citadel_core.zip;
            scp -oStrictHostKeyChecking=no install.sh ${ssh_connection}:install.sh;
            ssh -oStrictHostKeyChecking=no ${ssh_connection} <<< $'./install.sh';