version: 0.0.1
jobs:
  build:
    docker:
      - image: circleci/node:9.11.2-stretch

    working_directory: ~/repo/citadel_core

    steps:
      - checkout
        
      - run:
          name: Preparing to build
          command: |
            sudo npm i -g npm npx
            sudo npm i -g bestzip
        
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-

      - run:
          name: Installing dependencies
          command: |
            npm i
            
      - run:
          name: Building apidoc
          command: |
            npx apidoc -e node_modules

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
        
        
      - run:
          name: Deploying
          command: |
            bestzip "citadel_core.zip" *
            
            sftp -oStrictHostKeyChecking=no ${ssh_connection} <<< $'put citadel_core.zip';
            ssh -oStrictHostKeyChecking=no ${ssh_connection} <<< $'unzip citadel_core.zip -d /srv/citadel_core&&rm -f citadel_core.zip&&/srv/citadel_core/build.sh&&pm2 restart app';